### ISSUE TITLE
常见 flash 报错原因

### ISSUE THREAD

**Issue by 2betop** [fex-team/webuploader#294]
1.  flash 版本太低，请至少大于等于 11.4，低于此版本请提示更新 flash 版本
2. 按钮或者他的父级被设置 display:none 隐藏了，在这种情况下 flash 会停止运行，请改用以下方式隐藏，给 需要隐藏的元素加 `webuploader-element-invisible` 类名代替加 `display:none` 属性。
   
   ``` css
   .webuploader-element-invisible {
       position: absolute !important;
       clip: rect(1px 1px 1px 1px); /* IE6, IE7 */
       clip: rect(1px,1px,1px,1px);
   }
   ```
